"""add auth table

Revision ID: c5bad2a6c9e3
Revises: 590397c2b38b
Create Date: 2026-03-19 19:14:41.195007

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5bad2a6c9e3'
down_revision: Union[str, Sequence[str], None] = '590397c2b38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authmodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authmodel_email'), 'authmodel', ['email'], unique=True)
    op.create_index(op.f('ix_authmodel_username'), 'authmodel', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authmodel_username'), table_name='authmodel')
    op.drop_index(op.f('ix_authmodel_email'), table_name='authmodel')
    op.drop_table('authmodel')
    # ### end Alembic commands ###
